version: '3'
services:

  nexus:
    image: sonatype/nexus
    ports:
      - "8081:8081"
    container_name:
      nexus

  config-server:
    build: ./server/config-server
    ports:
      - "8082:8082"
    volumes:
      - ./server/config-server:/usr/src/app
    container_name:
      config-server
    command: ["./wait-for.sh", "-t", "1000", "nexus:8081", "--", "./mvnw", "-s", "maven-settings.xml", "spring-boot:run"]
    depends_on:
      - "nexus"

  discovery-server:
    build: ./server/discovery-server
    ports:
      - "8083:8083"
    volumes:
      - ./server/discovery-server:/usr/src/app
    container_name:
      discovery-server
    command: ["./wait-for.sh", "-t", "1000", "config-server:8082", "--", "./mvnw", "-s", "maven-settings.xml", "spring-boot:run"]
    depends_on:
      - "config-server"

  gateway-server:
    build: ./server/gateway-server
    ports:
      - "8080:8080"
    volumes:
      - ./server/gateway-server:/usr/src/app
    container_name:
      gateway-server
    command: ["./wait-for.sh", "-t", "1000", "discovery-server:8083", "--", "./mvnw", "-s", "maven-settings.xml", "spring-boot:run"]
    depends_on:
      - "discovery-server"

  produto-service:
    build: ./server/produto-service
    ports:
      - "8088:8088"
    volumes:
      - ./server/produto-service:/usr/src/app
    container_name:
      produto-service
    command: ["./wait-for.sh", "-t", "1000", "gateway-server:8080", "--", "./mvnw", "-s", "maven-settings.xml", "spring-boot:run"]
    depends_on:
      - "gateway-server"
